gitGraph:
    commit id:"init" tag:"v1.0"
    branch feature/new-releases
    checkout feature/new-releases
    commit id:"design"
    commit id:"frontend"
    checkout main
    commit id:"hotfix" type:HIGHLIGHT
    merge feature/new-releases tag:"v1.1"
    commit id:"analytics"
    branch feature/checkout
    checkout feature/checkout
    commit id:"payment" 